(venv)cboling@cord1-head1:~/SDNdbg$
(venv)cboling@cord1-head1:~/SDNdbg$ sudo python ./SDNdbg.py --config config2.yaml
/home/cboling/SDNdbg/core/config.py:78: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  config = yaml.load(f.read())



    u'stp-enabled': True}]
2016-12-07 14:52:15,631 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.20 - flat-building.cord.lab/compute-1 [07f6944a-bcbf-11e6-8d3a-b8ca3ab44c0c]': 'bool' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 273, in _trigger
    if t.execute(event):
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 174, in execute
    self._change_state(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 185, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 59, in enter
    event_data.machine._callback(oe, event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 579, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/cboling/SDNdbg/core/base.py", line 534, in on_enter_updating
    self.sync_object()
  File "/home/cboling/SDNdbg/core/base.py", line 507, in sync_object
    success = self.perform_sync() if self.client is not None else False
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 309, in perform_sync
    brctl_topology = self.get_brctl_topology(refresh=True)
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 156, in get_brctl_topology
    self._brctl_topology = BrctlClient.get_topology(self.ssh_address, self.ssh_username, self.ssh_password)
  File "/home/cboling/SDNdbg/linux/client.py", line 72, in get_topology
    return client._get_tables() if client is not None else None
  File "/home/cboling/SDNdbg/linux/client.py", line 88, in _get_tables
    self.table_info[table] = get_funcs.get(table)(connection)
  File "/home/cboling/SDNdbg/linux/client.py", line 170, in _get_interface_table
    devices = get_sys_class_net_interface_devices(connection)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 39, in get_sys_class_net_interface_devices
    return _get_device_list(connection, cmd_prefix)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 81, in _get_device_list
    if devices[name]['driver'].get('supports-statistics', 'no').lower() == 'yes':
AttributeError: 'bool' object has no attribute 'lower'
2016-12-07 14:52:15,632 INFO:SDNdbg:Sync: 10.6.0.8 - keystone/identity [07f738dc-bcbf-11e6-adc8-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a3567b50>
2016-12-07 14:52:15,632 INFO:SDNdbg:OpenStackNode [10.6.0.8 - keystone/identity]: Exited state out_of_sync
2016-12-07 14:52:15,633 INFO:SDNdbg:on_enter_updating: entry. 10.6.0.8 - keystone/identity
2016-12-07 14:52:15,633 INFO:SDNdbg:sync_object: entry. 10.6.0.8 - keystone/identity
2016-12-07 14:52:15,638 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.8, password: 'ubuntu'
2016-12-07 14:52:15,649 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:15,773 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: ubuntu@10.6.0.8: Bad authentication type
2016-12-07 14:52:15,891 INFO:SDNdbg:Attempting ssh connection: root@10.6.0.8, password: 'adtran'
2016-12-07 14:52:15,902 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:16,027 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: root@10.6.0.8: Bad authentication type
2016-12-07 14:52:16,144 INFO:SDNdbg:Attempting ssh connection: adtran@10.6.0.8, password: 'adtran'
2016-12-07 14:52:16,155 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:16,280 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: adtran@10.6.0.8: Bad authentication type
2016-12-07 14:52:16,394 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.8, password: 'ubuntu'
2016-12-07 14:52:16,405 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:16,514 INFO:SDNdbg:Authentication (publickey) successful!
2016-12-07 14:52:16,858 INFO:SDNdbg:output: []
2016-12-07 14:52:17,169 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.8 - keystone/identity [07f738dc-bcbf-11e6-adc8-b8ca3ab44c0c]': 'bool' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 273, in _trigger
    if t.execute(event):
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 174, in execute
    self._change_state(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 185, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 59, in enter
    event_data.machine._callback(oe, event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 579, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/cboling/SDNdbg/core/base.py", line 534, in on_enter_updating
    self.sync_object()
  File "/home/cboling/SDNdbg/core/base.py", line 507, in sync_object
    success = self.perform_sync() if self.client is not None else False
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 309, in perform_sync
    brctl_topology = self.get_brctl_topology(refresh=True)
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 156, in get_brctl_topology
    self._brctl_topology = BrctlClient.get_topology(self.ssh_address, self.ssh_username, self.ssh_password)
  File "/home/cboling/SDNdbg/linux/client.py", line 72, in get_topology
    return client._get_tables() if client is not None else None
  File "/home/cboling/SDNdbg/linux/client.py", line 88, in _get_tables
    self.table_info[table] = get_funcs.get(table)(connection)
  File "/home/cboling/SDNdbg/linux/client.py", line 170, in _get_interface_table
    devices = get_sys_class_net_interface_devices(connection)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 39, in get_sys_class_net_interface_devices
    return _get_device_list(connection, cmd_prefix)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 81, in _get_device_list
    if devices[name]['driver'].get('supports-statistics', 'no').lower() == 'yes':
AttributeError: 'bool' object has no attribute 'lower'
2016-12-07 14:52:17,170 INFO:SDNdbg:Sync: 10.6.0.13 - nova/compute [07f7d4b8-bcbf-11e6-9472-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a2cfe100>
2016-12-07 14:52:17,171 INFO:SDNdbg:OpenStackNode [10.6.0.13 - nova/compute]: Exited state out_of_sync
2016-12-07 14:52:17,171 INFO:SDNdbg:on_enter_updating: entry. 10.6.0.13 - nova/compute
2016-12-07 14:52:17,171 INFO:SDNdbg:sync_object: entry. 10.6.0.13 - nova/compute
2016-12-07 14:52:17,175 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.13, password: 'ubuntu'
2016-12-07 14:52:17,186 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:17,311 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: ubuntu@10.6.0.13: Bad authentication type
2016-12-07 14:52:17,429 INFO:SDNdbg:Attempting ssh connection: root@10.6.0.13, password: 'adtran'
2016-12-07 14:52:17,439 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:17,564 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: root@10.6.0.13: Bad authentication type
2016-12-07 14:52:17,682 INFO:SDNdbg:Attempting ssh connection: adtran@10.6.0.13, password: 'adtran'
2016-12-07 14:52:17,692 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:17,817 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: adtran@10.6.0.13: Bad authentication type
2016-12-07 14:52:17,932 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.13, password: 'ubuntu'
2016-12-07 14:52:17,943 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:18,051 INFO:SDNdbg:Authentication (publickey) successful!
2016-12-07 14:52:18,484 INFO:SDNdbg:output: []
2016-12-07 14:52:18,794 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.13 - nova/compute [07f7d4b8-bcbf-11e6-9472-b8ca3ab44c0c]': 'bool' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 273, in _trigger
    if t.execute(event):
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 174, in execute
    self._change_state(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 185, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 59, in enter
    event_data.machine._callback(oe, event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 579, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/cboling/SDNdbg/core/base.py", line 534, in on_enter_updating
    self.sync_object()
  File "/home/cboling/SDNdbg/core/base.py", line 507, in sync_object
    success = self.perform_sync() if self.client is not None else False
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 309, in perform_sync
    brctl_topology = self.get_brctl_topology(refresh=True)
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 156, in get_brctl_topology
    self._brctl_topology = BrctlClient.get_topology(self.ssh_address, self.ssh_username, self.ssh_password)
  File "/home/cboling/SDNdbg/linux/client.py", line 72, in get_topology
    return client._get_tables() if client is not None else None
  File "/home/cboling/SDNdbg/linux/client.py", line 88, in _get_tables
    self.table_info[table] = get_funcs.get(table)(connection)
  File "/home/cboling/SDNdbg/linux/client.py", line 170, in _get_interface_table
    devices = get_sys_class_net_interface_devices(connection)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 39, in get_sys_class_net_interface_devices
    return _get_device_list(connection, cmd_prefix)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 81, in _get_device_list
    if devices[name]['driver'].get('supports-statistics', 'no').lower() == 'yes':
AttributeError: 'bool' object has no attribute 'lower'
2016-12-07 14:52:18,795 INFO:SDNdbg:Sync: 10.6.0.12 - neutron/network [07f87c87-bcbf-11e6-97a2-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a2cfe5d0>
2016-12-07 14:52:18,795 INFO:SDNdbg:OpenStackNode [10.6.0.12 - neutron/network]: Exited state out_of_sync
2016-12-07 14:52:18,795 INFO:SDNdbg:on_enter_updating: entry. 10.6.0.12 - neutron/network
2016-12-07 14:52:18,796 INFO:SDNdbg:sync_object: entry. 10.6.0.12 - neutron/network
2016-12-07 14:52:18,799 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.12, password: 'ubuntu'
2016-12-07 14:52:18,810 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:18,918 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: ubuntu@10.6.0.12: Bad authentication type
2016-12-07 14:52:19,035 INFO:SDNdbg:Attempting ssh connection: root@10.6.0.12, password: 'adtran'
2016-12-07 14:52:19,046 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:19,171 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: root@10.6.0.12: Bad authentication type
2016-12-07 14:52:19,289 INFO:SDNdbg:Attempting ssh connection: adtran@10.6.0.12, password: 'adtran'
2016-12-07 14:52:19,299 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:19,425 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: adtran@10.6.0.12: Bad authentication type
2016-12-07 14:52:19,539 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.12, password: 'ubuntu'
2016-12-07 14:52:19,549 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:19,656 INFO:SDNdbg:Authentication (publickey) successful!
2016-12-07 14:52:20,052 INFO:SDNdbg:output: []
2016-12-07 14:52:20,397 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.12 - neutron/network [07f87c87-bcbf-11e6-97a2-b8ca3ab44c0c]': 'bool' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 273, in _trigger
    if t.execute(event):
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 174, in execute
    self._change_state(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 185, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 59, in enter
    event_data.machine._callback(oe, event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 579, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/cboling/SDNdbg/core/base.py", line 534, in on_enter_updating
    self.sync_object()
  File "/home/cboling/SDNdbg/core/base.py", line 507, in sync_object
    success = self.perform_sync() if self.client is not None else False
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 309, in perform_sync
    brctl_topology = self.get_brctl_topology(refresh=True)
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 156, in get_brctl_topology
    self._brctl_topology = BrctlClient.get_topology(self.ssh_address, self.ssh_username, self.ssh_password)
  File "/home/cboling/SDNdbg/linux/client.py", line 72, in get_topology
    return client._get_tables() if client is not None else None
  File "/home/cboling/SDNdbg/linux/client.py", line 88, in _get_tables
    self.table_info[table] = get_funcs.get(table)(connection)
  File "/home/cboling/SDNdbg/linux/client.py", line 170, in _get_interface_table
    devices = get_sys_class_net_interface_devices(connection)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 39, in get_sys_class_net_interface_devices
    return _get_device_list(connection, cmd_prefix)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 81, in _get_device_list
    if devices[name]['driver'].get('supports-statistics', 'no').lower() == 'yes':
AttributeError: 'bool' object has no attribute 'lower'
2016-12-07 14:52:20,399 INFO:SDNdbg:Sync: 10.6.0.21 - valid-basin.cord.lab/compute-2 [07f93507-bcbf-11e6-87eb-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a2cfe9f0>
2016-12-07 14:52:20,399 INFO:SDNdbg:OpenStackNode [10.6.0.21 - valid-basin.cord.lab/compute-2]: Exited state out_of_sync
2016-12-07 14:52:20,399 INFO:SDNdbg:on_enter_updating: entry. 10.6.0.21 - valid-basin.cord.lab/compute-2
2016-12-07 14:52:20,399 INFO:SDNdbg:sync_object: entry. 10.6.0.21 - valid-basin.cord.lab/compute-2
2016-12-07 14:52:20,405 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.21, password: 'ubuntu'
2016-12-07 14:52:20,410 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:20,508 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: ubuntu@10.6.0.21: Bad authentication type
2016-12-07 14:52:20,625 INFO:SDNdbg:Attempting ssh connection: root@10.6.0.21, password: 'adtran'
2016-12-07 14:52:20,634 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:20,759 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: root@10.6.0.21: Bad authentication type
2016-12-07 14:52:20,877 INFO:SDNdbg:Attempting ssh connection: adtran@10.6.0.21, password: 'adtran'
2016-12-07 14:52:20,886 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:21,011 WARNING:SDNdbg:OpenStack.linux_bridges: SSH Authentication Exception: adtran@10.6.0.21: Bad authentication type
2016-12-07 14:52:21,125 INFO:SDNdbg:Attempting ssh connection: ubuntu@10.6.0.21, password: 'ubuntu'
2016-12-07 14:52:21,134 INFO:SDNdbg:Connected (version 2.0, client OpenSSH_6.6.1p1)
2016-12-07 14:52:21,241 INFO:SDNdbg:Authentication (publickey) successful!
2016-12-07 14:52:21,576 INFO:SDNdbg:output: [ { u'id': '8000.0242bc01e431',
    u'interfaces': [],
    u'name': 'docker0',
    u'stp-enabled': False},
  { u'id': '8000.0cc47aa8b922',
    u'interfaces': ['eth2', 'eth3', 'eth4', 'eth5', 'eth6', 'eth7'],
    u'name': 'mgmtbr',
    u'stp-enabled': False},
  { u'id': '8000.5254003e6f7f',
    u'interfaces': ['virbr0-nic'],
    u'name': 'virbr0',
    u'stp-enabled': True}]
2016-12-07 14:52:21,939 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.21 - valid-basin.cord.lab/compute-2 [07f93507-bcbf-11e6-87eb-b8ca3ab44c0c]': 'bool' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 273, in _trigger
    if t.execute(event):
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 174, in execute
    self._change_state(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 185, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 59, in enter
    event_data.machine._callback(oe, event_data)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 579, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/home/cboling/SDNdbg/core/base.py", line 534, in on_enter_updating
    self.sync_object()
  File "/home/cboling/SDNdbg/core/base.py", line 507, in sync_object
    success = self.perform_sync() if self.client is not None else False
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 309, in perform_sync
    brctl_topology = self.get_brctl_topology(refresh=True)
  File "/home/cboling/SDNdbg/openstack/openstacknode.py", line 156, in get_brctl_topology
    self._brctl_topology = BrctlClient.get_topology(self.ssh_address, self.ssh_username, self.ssh_password)
  File "/home/cboling/SDNdbg/linux/client.py", line 72, in get_topology
    return client._get_tables() if client is not None else None
  File "/home/cboling/SDNdbg/linux/client.py", line 88, in _get_tables
    self.table_info[table] = get_funcs.get(table)(connection)
  File "/home/cboling/SDNdbg/linux/client.py", line 170, in _get_interface_table
    devices = get_sys_class_net_interface_devices(connection)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 39, in get_sys_class_net_interface_devices
    return _get_device_list(connection, cmd_prefix)
  File "/home/cboling/SDNdbg/linux/sys_class_net.py", line 81, in _get_device_list
    if devices[name]['driver'].get('supports-statistics', 'no').lower() == 'yes':
AttributeError: 'bool' object has no attribute 'lower'
2016-12-07 14:52:21,940 INFO:SDNdbg:Sync: onos-cord-1 [0782ff75-bcbf-11e6-950c-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6ac5a6a48>
2016-12-07 14:52:21,940 INFO:SDNdbg:Controller [onos-cord-1]: Exited state out_of_sync
2016-12-07 14:52:21,941 INFO:SDNdbg:on_enter_updating: entry. onos-cord-1
2016-12-07 14:52:21,941 INFO:SDNdbg:sync_object: entry. onos-cord-1
2016-12-07 14:52:21,941 INFO:SDNdbg:Controller [onos-cord-1]: Entered state updating
2016-12-07 14:52:21,941 INFO:SDNdbg:on_exit_updating: entry. onos-cord-1
2016-12-07 14:52:21,941 INFO:SDNdbg:Controller [onos-cord-1]: Exited state updating
2016-12-07 14:52:21,942 INFO:SDNdbg:Controller [onos-cord-1]: Entered state in_sync
2016-12-07 14:52:21,942 INFO:SDNdbg:Sync: onos-cord-1 [0782ff75-bcbf-11e6-950c-b8ca3ab44c0c], 0 children
2016-12-07 14:52:21,942 INFO:SDNdbg:Sync: onos-fabric-1 [07837263-bcbf-11e6-b0c0-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6ac5a6f18>
2016-12-07 14:52:21,942 INFO:SDNdbg:Controller [onos-fabric-1]: Exited state out_of_sync
2016-12-07 14:52:21,943 INFO:SDNdbg:on_enter_updating: entry. onos-fabric-1
2016-12-07 14:52:21,943 INFO:SDNdbg:sync_object: entry. onos-fabric-1
2016-12-07 14:52:21,943 INFO:SDNdbg:Controller [onos-fabric-1]: Entered state updating
2016-12-07 14:52:21,943 INFO:SDNdbg:on_exit_updating: entry. onos-fabric-1
2016-12-07 14:52:21,943 INFO:SDNdbg:Controller [onos-fabric-1]: Exited state updating
2016-12-07 14:52:21,944 INFO:SDNdbg:Controller [onos-fabric-1]: Entered state in_sync
2016-12-07 14:52:21,944 INFO:SDNdbg:Sync: onos-fabric-1 [07837263-bcbf-11e6-b0c0-b8ca3ab44c0c], 0 children
2016-12-07 14:52:26,944 INFO:SDNdbg:Sync: OpenCORD [077b3980-bcbf-11e6-a039-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a4292158>
2016-12-07 14:52:26,945 INFO:SDNdbg:Site [OpenCORD]: Exited state in_sync
2016-12-07 14:52:26,945 INFO:SDNdbg:on_enter_updating: entry. OpenCORD
2016-12-07 14:52:26,945 INFO:SDNdbg:sync_object: entry. OpenCORD
2016-12-07 14:52:26,945 INFO:SDNdbg:Site [OpenCORD]: Entered state updating
2016-12-07 14:52:26,946 INFO:SDNdbg:on_exit_updating: entry. OpenCORD
2016-12-07 14:52:26,946 INFO:SDNdbg:Site [OpenCORD]: Exited state updating
2016-12-07 14:52:26,946 INFO:SDNdbg:Site [OpenCORD]: Entered state in_sync
2016-12-07 14:52:26,946 INFO:SDNdbg:Sync: OpenCORD [077b3980-bcbf-11e6-a039-b8ca3ab44c0c], 3 children
2016-12-07 14:52:26,946 INFO:SDNdbg:Sync: OpenCORD [07829d23-bcbf-11e6-859e-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6ac5a6578>
2016-12-07 14:52:26,947 INFO:SDNdbg:Controller [OpenCORD]: Exited state in_sync
2016-12-07 14:52:26,947 INFO:SDNdbg:on_enter_updating: entry. OpenCORD
2016-12-07 14:52:26,947 INFO:SDNdbg:sync_object: entry. OpenCORD
2016-12-07 14:52:27,865 INFO:SDNdbg:Controller [OpenCORD]: Entered state updating
2016-12-07 14:52:27,865 INFO:SDNdbg:on_exit_updating: entry. OpenCORD
2016-12-07 14:52:27,869 INFO:SDNdbg:Controller [OpenCORD]: Exited state updating
2016-12-07 14:52:27,871 INFO:SDNdbg:Controller [OpenCORD]: Entered state in_sync
2016-12-07 14:52:27,871 INFO:SDNdbg:Sync: OpenCORD [07829d23-bcbf-11e6-859e-b8ca3ab44c0c], 5 children
2016-12-07 14:52:27,871 INFO:SDNdbg:Sync: 10.6.0.20 - flat-building.cord.lab/compute-1 [07f6944a-bcbf-11e6-8d3a-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a3567470>
2016-12-07 14:52:27,872 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.20 - flat-building.cord.lab/compute-1 [07f6944a-bcbf-11e6-8d3a-b8ca3ab44c0c]':
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 268, in _trigger
    raise MachineError(msg)
MachineError: u"OpenStackNode [10.6.0.20 - flat-building.cord.lab/compute-1]: Can't trigger event tick from state updating!"
2016-12-07 14:52:27,872 INFO:SDNdbg:Sync: 10.6.0.8 - keystone/identity [07f738dc-bcbf-11e6-adc8-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a3567b50>
2016-12-07 14:52:27,872 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.8 - keystone/identity [07f738dc-bcbf-11e6-adc8-b8ca3ab44c0c]':
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 268, in _trigger
    raise MachineError(msg)
MachineError: u"OpenStackNode [10.6.0.8 - keystone/identity]: Can't trigger event tick from state updating!"
2016-12-07 14:52:27,873 INFO:SDNdbg:Sync: 10.6.0.13 - nova/compute [07f7d4b8-bcbf-11e6-9472-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a2cfe100>
2016-12-07 14:52:27,873 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.13 - nova/compute [07f7d4b8-bcbf-11e6-9472-b8ca3ab44c0c]':
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 268, in _trigger
    raise MachineError(msg)
MachineError: u"OpenStackNode [10.6.0.13 - nova/compute]: Can't trigger event tick from state updating!"
2016-12-07 14:52:27,874 INFO:SDNdbg:Sync: 10.6.0.12 - neutron/network [07f87c87-bcbf-11e6-97a2-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a2cfe5d0>
2016-12-07 14:52:27,874 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.12 - neutron/network [07f87c87-bcbf-11e6-97a2-b8ca3ab44c0c]':
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 268, in _trigger
    raise MachineError(msg)
MachineError: u"OpenStackNode [10.6.0.12 - neutron/network]: Can't trigger event tick from state updating!"
2016-12-07 14:52:27,874 INFO:SDNdbg:Sync: 10.6.0.21 - valid-basin.cord.lab/compute-2 [07f93507-bcbf-11e6-87eb-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6a2cfe9f0>
2016-12-07 14:52:27,875 ERROR:SDNdbg:Unhandled Exception while attempting to sync '10.6.0.21 - valid-basin.cord.lab/compute-2 [07f93507-bcbf-11e6-87eb-b8ca3ab44c0c]':
Traceback (most recent call last):
  File "/home/cboling/SDNdbg/core/base.py", line 568, in sync
    self.tick()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 248, in trigger
    return self.machine._process(f)
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 600, in _process
    self._transition_queue[0]()
  File "/home/cboling/SDNdbg/venv/lib/python2.7/site-packages/transitions/core.py", line 268, in _trigger
    raise MachineError(msg)
MachineError: u"OpenStackNode [10.6.0.21 - valid-basin.cord.lab/compute-2]: Can't trigger event tick from state updating!"
2016-12-07 14:52:27,875 INFO:SDNdbg:Sync: onos-cord-1 [0782ff75-bcbf-11e6-950c-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6ac5a6a48>
2016-12-07 14:52:27,875 INFO:SDNdbg:Controller [onos-cord-1]: Exited state in_sync
2016-12-07 14:52:27,876 INFO:SDNdbg:on_enter_updating: entry. onos-cord-1
2016-12-07 14:52:27,876 INFO:SDNdbg:sync_object: entry. onos-cord-1
2016-12-07 14:52:27,876 INFO:SDNdbg:Controller [onos-cord-1]: Entered state updating
2016-12-07 14:52:27,876 INFO:SDNdbg:on_exit_updating: entry. onos-cord-1
2016-12-07 14:52:27,876 INFO:SDNdbg:Controller [onos-cord-1]: Exited state updating
2016-12-07 14:52:27,877 INFO:SDNdbg:Controller [onos-cord-1]: Entered state in_sync
2016-12-07 14:52:27,877 INFO:SDNdbg:Sync: onos-cord-1 [0782ff75-bcbf-11e6-950c-b8ca3ab44c0c], 0 children
2016-12-07 14:52:27,877 INFO:SDNdbg:Sync: onos-fabric-1 [07837263-bcbf-11e6-b0c0-b8ca3ab44c0c] entry: no sync: False, deleted: <functools.partial object at 0x7fa6ac5a6f18>
2016-12-07 14:52:27,877 INFO:SDNdbg:Controller [onos-fabric-1]: Exited state in_sync
2016-12-07 14:52:27,877 INFO:SDNdbg:on_enter_updating: entry. onos-fabric-1
2016-12-07 14:52:27,878 INFO:SDNdbg:sync_object: entry. onos-fabric-1
2016-12-07 14:52:27,878 INFO:SDNdbg:Controller [onos-fabric-1]: Entered state updating
2016-12-07 14:52:27,878 INFO:SDNdbg:on_exit_updating: entry. onos-fabric-1
2016-12-07 14:52:27,878 INFO:SDNdbg:Controller [onos-fabric-1]: Exited state updating
2016-12-07 14:52:27,879 INFO:SDNdbg:Controller [onos-fabric-1]: Entered state in_sync
2016-12-07 14:52:27,879 INFO:SDNdbg:Sync: onos-fabric-1 [07837263-bcbf-11e6-b0c0-b8ca3ab44c0c], 0 children
^V^V^V^V^V^V^C^C2016-12-07 14:52:31,772 INFO:SDNdbg:^C from keyboard captured, shutting down gracefully
2016-12-07 14:52:31,772 INFO:SDNdbg:Signaling Shutdown
2016-12-07 14:52:31,772 INFO:SDNdbg:Halting up synchronization thread for OpenCORD, delay: 5.0
2016-12-07 14:52:31,802 INFO:SDNdbg:Sync:Thread: OpenCORD thread exiting
^C2016-12-07 14:52:31,804 INFO:SDNdbg:Signaling Shutdown
Traceback (most recent call last):
  File "./SDNdbg.py", line 133, in <module>
    main()
  File "./SDNdbg.py", line 121, in main
    shutdown(5.0)
  File "./SDNdbg.py", line 62, in shutdown
    SyncThread.stop_all_threads(wait_delay)
  File "/home/cboling/SDNdbg/core/sync.py", line 83, in stop_all_threads
    item.stop(wait_delay)
  File "/home/cboling/SDNdbg/core/sync.py", line 132, in stop
    self._thread.join(wait_delay)
  File "/home/cboling/python/lib/python2.7/threading.py", line 951, in join
    self.__block.wait(delay)
  File "/home/cboling/python/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
^C(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$ ^C
(venv)cboling@cord1-head1:~/SDNdbg$
